name = "sequencelib"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Sequencelib"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4.git"
rev = "v4.18.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.18.0"

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl"
rev = "v4.18.0"

[[lean_lib]]
name = "Sequencelib"
